BlogTemplate/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BlogTemplate._1.Models
{
    public class Post
    {
        public Guid Id { get; set; }
        public List<Comment> Comments { get; set; } = new List<Comment>();
        [Required(ErrorMessage = "Title required")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Post text required")]
        public string Body { get; set; }
        public DateTimeOffset PubDate { get; set; }
        public DateTimeOffset LastModified { get; set; } = DateTimeOffset.Now;
        public string Slug{ get; set; }
        public bool IsPublic { get; set; }
        public bool IsDeleted { get; set; }
        public string Excerpt { get; set; }
        public int ExcerptMaxLength { get; } = 140;
    }
}

BlogTemplate/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlogTemplate._1.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your blog description page.";
        }
    }
}

BlogTemplate/Pages/Drafts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BlogTemplate._1.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlogTemplate._1.Pages
{
    public class DraftsModel : PageModel
    {
        const string StorageFolder = "BlogFiles";

        private readonly BlogDataStore _dataStore;

        public IEnumerable<DraftSummaryModel> DraftSummaries { get; private set; }

        public DraftsModel(BlogDataStore dataStore)
        {
            _dataStore = dataStore;
        }

        public void OnGet()
        {
            Func<Post, bool> postFilter = p => !p.IsPublic;
            IEnumerable<Post> postModels = _dataStore.GetAllDrafts().Where(postFilter);

            DraftSummaries = postModels.Select(p => new DraftSummaryModel
            {
                Id = p.Id,
                Slug = p.Slug,
                Title = p.Title,
                Excerpt = p.Excerpt,
                PublishTime = p.PubDate,
                CommentCount = p.Comments.Count,
            });
        }
    }

    public class DraftSummaryModel
    {
        public Guid Id { get; set; }
        public string Slug { get; set; }
        public string Title { get; set; }
        public DateTimeOffset PublishTime { get; set; }
        public string Excerpt { get; set; }
        public int CommentCount { get; set; }
    }
}


BlogTemplate/Pages/Edit.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using BlogTemplate._1.Models;
using BlogTemplate._1.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace BlogTemplate._1.Pages
{
    [Authorize]
    public class EditModel : PageModel
    {
        private readonly BlogDataStore _dataStore;
        private readonly SlugGenerator _slugGenerator;
        private readonly ExcerptGenerator _excerptGenerator;

        public EditModel(BlogDataStore dataStore, SlugGenerator slugGenerator, ExcerptGenerator excerptGenerator)
        {
            _dataStore = dataStore;
            _slugGenerator = slugGenerator;
            _excerptGenerator = excerptGenerator;
        }

        [BindProperty]
        public EditedPostModel EditedPost { get; set; }
        public bool hasSlug { get; set; }

        public void OnGet([FromRoute] string id)
        {
            Post post = _dataStore.GetPost(id);

            if (post == null)
            {
                RedirectToPage("/Index");
            }

            EditedPost = new EditedPostModel
            {
                Title = post.Title,
                Body = post.Body,
                Excerpt = post.Excerpt,
            };

            hasSlug = !string.IsNullOrEmpty(post.Slug);

            ViewData["Slug"] = post.Slug;
            ViewData["id"] = post.Id;
        }

        [ValidateAntiForgeryToken]
        public IActionResult OnPostPublish([FromRoute] string id, [FromForm] bool updateSlug)
        {
            Post post = _dataStore.GetPost(id);
            if (ModelState.IsValid)
            {
                bool wasPublic = post.IsPublic;
                post.IsPublic = true;
                if (post.PubDate.Equals(default(DateTimeOffset)))
                {
                    post.PubDate = DateTimeOffset.Now;
                }
                if (!hasSlug)
                {
                    post.Slug = _slugGenerator.CreateSlug(post.Title);
                }
                UpdatePost(post, updateSlug, wasPublic);
            }
            return Redirect($"/Post/{id}/{post.Slug}");
        }

        [ValidateAntiForgeryToken]
        public IActionResult OnPostSaveDraft([FromRoute] string id)
        {
            Post post = _dataStore.GetPost(id);
            if (ModelState.IsValid)
            {
                bool wasPublic = post.IsPublic;
                post.IsPublic = false;
                UpdatePost(post, false, wasPublic);
            }
            return Redirect("/Drafts");
        }

        private void UpdatePost(Post post, [FromForm] bool updateSlug, bool wasPublic)
        {
            post.Title = EditedPost.Title;
            post.Body = EditedPost.Body;
            if (string.IsNullOrEmpty(EditedPost.Excerpt))
            {
                EditedPost.Excerpt = _excerptGenerator.CreateExcerpt(EditedPost.Body);
            }
            post.Excerpt = EditedPost.Excerpt;

            if (updateSlug)
            {
                post.Slug = _slugGenerator.CreateSlug(post.Title);
            }
            if (Request != null)
            {
                _dataStore.SaveFiles(Request.Form.Files.ToList());
            }
            _dataStore.UpdatePost(post, wasPublic);
        }
        public class EditedPostModel
        {
            [Required]
            public string Title { get; set; }
            [Required]
            public string Body { get; set; }
            public string Excerpt { get; set; }
        }
    }
}

BlogTemplate/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlogTemplate._1.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BlogTemplate/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BlogTemplate._1.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlogTemplate._1.Pages
{
    public class IndexModel : PageModel
    {
        const string StorageFolder = "BlogFiles";

        private readonly BlogDataStore _dataStore;

        public IEnumerable<PostSummaryModel> PostSummaries { get; private set; }

        public IndexModel(BlogDataStore dataStore)
        {
            _dataStore = dataStore;
        }

        public void OnGet()
        {
            Func<Post, bool> postFilter = p => p.IsPublic;
            Func<Post, bool> deletedPostFilter = p => !p.IsDeleted;
            IEnumerable<Post> postModels = _dataStore.GetAllPosts().Where(postFilter).Where(deletedPostFilter);

            PostSummaries = postModels.Select(p => new PostSummaryModel {
                Id = p.Id,
                Slug = p.Slug,
                Title = p.Title,
                Excerpt = p.Excerpt,
                PublishTime = p.PubDate,
                CommentCount = p.Comments.Where(c => c.IsPublic).Count(),
            });
        }

        public class PostSummaryModel
        {
            public Guid Id { get; set; }
            public string Slug { get; set; }
            public string Title { get; set; }
            public DateTimeOffset PublishTime { get; set; }
            public string Excerpt { get; set; }
            public int CommentCount { get; set; }
       }
    }
}

BlogTemplate/Pages/ManageComment.cshtml.cs
using System;
using BlogTemplate._1.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlogTemplate._1.Pages
{
    [Authorize]
    public class ManageCommentModel : PageModel
    {
        private readonly BlogDataStore _dataStore;

        public ManageCommentModel(BlogDataStore dataStore)
        {
            _dataStore = dataStore;
        }

        [ValidateAntiForgeryToken]
        public IActionResult OnPostDeleteComment(Guid commentId, string id)
        {
            Post post = _dataStore.GetPost(id);

            Comment foundComment = _dataStore.FindComment(commentId, post);
            foundComment.IsPublic = false;

            _dataStore.SavePost(post);
            return Redirect($"/Post/{id}/{post.Slug}");
        }

        [ValidateAntiForgeryToken]
        public IActionResult OnPostUndeleteComment(Guid commentId, string id)
        {
            Post post = _dataStore.GetPost(id);

            Comment foundComment = _dataStore.FindComment(commentId, post);
            foundComment.IsPublic = true;

            _dataStore.SavePost(post);
            return Redirect($"/Post/{id}/{post.Slug}");
        }
    }
}

BlogTemplate/Pages/New.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using BlogTemplate._1.Models;
using BlogTemplate._1.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace BlogTemplate._1.Pages
{
    [Authorize]
    public class NewModel : PageModel
    {
        private readonly BlogDataStore _dataStore;
        private readonly SlugGenerator _slugGenerator;
        private readonly ExcerptGenerator _excerptGenerator;

        public NewModel(BlogDataStore dataStore, SlugGenerator slugGenerator, ExcerptGenerator excerptGenerator)
        {
            _dataStore = dataStore;
            _slugGenerator = slugGenerator;
            _excerptGenerator = excerptGenerator;
        }

        [BindProperty]
        public NewPostViewModel NewPost { get; set; }

        public void OnGet()
        {           
        }

        [ValidateAntiForgeryToken]
        public IActionResult OnPostPublish()
        {
            if (ModelState.IsValid)
            {
                SavePost(NewPost, true);
                return Redirect("/Index");
            }

            return Page();
        }

        [ValidateAntiForgeryToken]
        public IActionResult OnPostSaveDraft()
        {
            if(ModelState.IsValid)
            {
                SavePost(NewPost, false);
                return Redirect("/Drafts");
            }

            return Page();
        }
        
        private void SavePost(NewPostViewModel newPost, bool publishPost)
        {
            if (string.IsNullOrEmpty(newPost.Excerpt))
            {
                newPost.Excerpt = _excerptGenerator.CreateExcerpt(newPost.Body);
            }

            Post post = new Post {
                Title = newPost.Title,
                Body = newPost.Body,
                Excerpt = newPost.Excerpt,
                Slug = _slugGenerator.CreateSlug(newPost.Title),
                LastModified = DateTimeOffset.Now,
                IsDeleted = false,
            };

            if (publishPost)
            {
                post.PubDate = DateTimeOffset.Now;
                post.IsPublic = true;
            }

            if (Request != null)
            {
                _dataStore.SaveFiles(Request.Form.Files.ToList());
            }

            _dataStore.SavePost(post);
        }

        public class NewPostViewModel
        {
            [Required]
            public string Title { get; set; }
            [Required]
            public string Body { get; set; }
            public string Excerpt { get; set; }
        }
    }
}

BlogTemplate/Pages/Post.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using BlogTemplate._1.Models;
using BlogTemplate._1.Services;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlogTemplate._1.Pages
{

    public class PostModel : PageModel
    {
        private readonly BlogDataStore _dataStore;
        private readonly MarkdownRenderer _markdownRenderer;
        const int MaxAllowedComments = 100;

        public PostModel(BlogDataStore dataStore, MarkdownRenderer markdownRenderer)
        {
            _dataStore = dataStore;
            _markdownRenderer = markdownRenderer;
        }

        public Post Post { get; set; }
        public bool IsCommentsFull => Post.Comments.Count >= MaxAllowedComments;

        public HtmlString HtmlBody()
        {
            var html = _markdownRenderer.RenderMarkdown(Post.Body);
            return html;
        }

        public void OnGet([FromRoute] string id)
        {
            Post = _dataStore.GetPost(id);

            if (Post == null || !Post.IsPublic)
            {
                RedirectToPage("/Index");
            }
        }

        public IActionResult ChangeState(bool Deleted, string id)
        {
            Post = _dataStore.GetPost(id);

            if (ModelState.IsValid)
            {
                Post.IsDeleted = Deleted;
                _dataStore.SavePost(Post);
                return RedirectToPage("/Index");
            }
            return Redirect("/post/" + id + "/" + Post.Slug);
        }

        [ValidateAntiForgeryToken]
        public IActionResult OnPostDeletePost([FromRoute] string id)
        {
            return ChangeState(true, id);
        }

        [ValidateAntiForgeryToken]
        public IActionResult OnPostUnDeletePost([FromRoute] string id)
        {
            return ChangeState(false, id);
        }

        [ValidateAntiForgeryToken]
        public IActionResult OnPostPublishComment([FromRoute] string id, [FromForm] CommentViewModel NewComment)
        {
            Post = _dataStore.GetPost(id);

            if (Post == null)
            {
                return RedirectToPage("/Index");
            }
            else if (ModelState.IsValid)
            {
                Comment comment = new Comment
                {
                    AuthorName = NewComment.AuthorName,
                    Body = NewComment.Body,
                };
                comment.IsPublic = true;
                comment.UniqueId = Guid.NewGuid();
                Post.Comments.Add(comment);
                _dataStore.SavePost(Post);
                return Redirect("/post/" + id + "/" + Post.Slug);
            }

            return Page();
        }

        public class CommentViewModel
        {
            [Required]
            [MaxLength(100, ErrorMessage = "You have exceeded the maximum length of 100 characters")]
            public string AuthorName { get; set; }
            [Required]
            [MaxLength(1000, ErrorMessage = "You have exceeded the maximum length of 1000 characters")]
            public string Body { get; set; }
        }
    }
}

BlogTemplate/Pages/Trash.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogTemplate._1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlogTemplate._1.Pages
{
    public class TrashModel : PageModel
    {
        const string StorageFolder = "BlogFiles";

        private readonly BlogDataStore _dataStore;

        public IEnumerable<PostSummaryModel> PostSummaries { get; private set; }

        public TrashModel(BlogDataStore dataStore)
        {
            _dataStore = dataStore;
        }

        public void OnGet()
        {
            Func<Post, bool> deletedPostFilter = p => p.IsDeleted;
            IEnumerable<Post> postModels = _dataStore.GetAllPosts().Where(deletedPostFilter);

            PostSummaries = postModels.Select(p => new PostSummaryModel
            {
                Id = p.Id,
                Slug = p.Slug,
                Title = p.Title,
                Excerpt = p.Excerpt,
                PublishTime = p.PubDate,
                CommentCount = p.Comments.Where(c => c.IsPublic).Count(),
            });
        }

        public class PostSummaryModel
        {
            public Guid Id { get; set; }
            public string Slug { get; set; }
            public string Title { get; set; }
            public DateTimeOffset PublishTime { get; set; }
            public string Excerpt { get; set; }
            public int CommentCount { get; set; }
        }
    }
}

BlogTemplate/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

BlogTemplate/Pages/AlreadyRegistered.cshtml
@page
@{
    ViewData["Title"] = "Already Registered";
}

<h1>You are already registered.</h1>

BlogTemplate/Pages/Drafts.cshtml
@page
@model DraftsModel
@{
    ViewData["Title"] = "Drafts";

    <h2>@ViewData["Title"]</h2>

    if (!Model.DraftSummaries.Any())
    {
        <p>View and edit your saved drafts here.</p>
    }
    else
    {
        foreach (var post in Model.DraftSummaries)
        {
            <article>
                <div class="col-md-12">
                    <h2><a asp-page="/edit" asp-route-id="@post.Id.ToString("N")" asp-route-slug="@post.Slug">@post.Title</a></h2>
                    @if (post.PublishTime != default(DateTimeOffset))
                    {
                        <div class="h5 text-muted">Last Published @post.PublishTime.ToString("MMM dd, yyyy")</div>
                    }
                    <p class="lead">@post.Excerpt</p>
                    <h4><a href="/post/@post.Id.ToString("N")/@post.Slug"><span class="glyphicon glyphicon-comment"></span> @post.CommentCount</a></h4>
                </div>
            </article>
        }
    }
}

BlogTemplate/Pages/Edit.cshtml
@page "{id}"
@model EditModel
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

@using BlogTemplate._1
@using BlogTemplate._1.Models
@using Microsoft.AspNetCore.Mvc.RazorPages

@{
    ViewData["Title"] = "Edit Post";
}

<article>
    <h2>Edit Post</h2>
    <div class="col-md-12 well">
        <form method="post" id="editpost" enctype="multipart/form-data" data-has-slug="@Model.hasSlug">
            @if (TempData["notice"] != null)
            {
                <h3>@TempData["notice"]</h3>
            }
            <div class="form-group col-md-6">
                <label for="Title">Title</></label>
                <input type="text" class="form-control" placeholder="" asp-for="EditedPost.Title" data-oldtitle="@Model.EditedPost.Title" />
                <span asp-validation-for="EditedPost.Title" class="text-warning"></span>
            </div>
            <input type="hidden" name="updateSlug" id="updateSlug" value="false" />
            <div class="col-md-12 form-group">
                <label for="Body" class="primaryField">Body</label>
                <textarea rows="10" class="form-control" placeholder="" asp-for="EditedPost.Body" id="post-body"></textarea>
                <span asp-validation-for="EditedPost.Body" class="text-warning"></span>
            </div>
            <div class="col-md-12 form-group">
                <label for="Excerpt" class="secondaryField">Excerpt (Optional)</label>
                <textarea class="form-control" placeholder="" asp-for="EditedPost.Excerpt"></textarea>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label>Upload Files</label>
                    <input type="file" name="files" multiple id="file-input" onchange="insertFiles()" />
                </div>
            </div>
            <div class="col-md-12">
                <input type="submit" name="save" class="btn btn-primary btn-sm" value="Save Draft" asp-page-handler="SaveDraft" />
                <input type="submit" name="publish" id="postsave" class="btn btn-primary btn-sm" value="Publish" asp-page-handler="Publish" />
            </div>
            <div class="col-md-12">
                <p class="cancel-link"><a asp-page="/post" asp-route-id="@ViewData["id"]" asp-route-slug="@ViewData["Slug"]"><span class="glyphicon glyphicon-triangle-left"></span> Cancel and Undo Changes</a></p>
            </div>
        </form>
    </div>
</article>

@section Scripts {
    <script src="~/js/updateBody.js"></script>
    <script src="~/js/slugUpdateWarning.js"></script>
}

BlogTemplate/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home Page";

    if (!Model.PostSummaries.Any())
    {
        <div class="jumbotron">
            <h1>Welcome!</h1>
            <p>Get started and write your first blog post <a class="text-primary" asp-page="/New">here</a>.</p>
            <p>Happy blogging!</p>
        </div>
    }

    else
    {
        foreach (var post in Model.PostSummaries)
        {
            <article>
                <div class="col-md-12">
                    <h2><a asp-page="/post" asp-route-id="@post.Id.ToString("N")" asp-route-slug="@post.Slug">@post.Title</a></h2>
                    <div class="h5 text-muted">@post.PublishTime.ToString("MMM dd, yyyy")</div> 
                    <p class="lead">@post.Excerpt</p>
                    <div class="h4"><a asp-page="/post" asp-route-id="@post.Id.ToString("N")" asp-route-slug="@post.Slug"><span class="glyphicon glyphicon-comment"></span> @post.CommentCount</a></div>
                </div>
            </article>
        }
    }
}

BlogTemplate/Pages/ManageComment.cshtml
@page "{id}/{handler?}"
@model ManageCommentModel
@{
}

BlogTemplate/Pages/New.cshtml
@page
@model NewModel
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

@using BlogTemplate._1
@using BlogTemplate._1.Models
@using Microsoft.AspNetCore.Mvc.RazorPages

@{
    ViewData["Title"] = "New Blog Post";
}

<h2>Write a New Post</h2>

<form method="POST" enctype="multipart/form-data">
    <div class="col-md-12 well">
        <div class="form-group col-md-6">
            <label for="Title">Title</></label>
            <input type="text" class="form-control" placeholder="" asp-for="NewPost.Title" />
            <span asp-validation-for="NewPost.Title" class="text-warning"></span>
        </div>
        <div class="form-group col-md-12">
            <label for="Body" class="primaryField">Body</label>
            <textarea rows="10" class="form-control" placeholder="" asp-for="NewPost.Body" id="post-body"></textarea>
            <span asp-validation-for="NewPost.Body" class="text-warning"></span>
        </div>
        <div class="form-group col-md-12">
            <label for="Excerpt" class="secondaryField">Excerpt (Optional)</label>
            <textarea class="form-control" placeholder="" asp-for="NewPost.Excerpt"></textarea>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label>Upload Files</label>
                <input type="file" name="files" multiple id="file-input" onchange="insertFiles()" />
            </div>
        </div>
        <div class="col-md-12">
            <input type="submit" name="save" class="btn btn-primary btn-sm" value="Save Draft" asp-page-handler="SaveDraft" />
            <input type="submit" name="publish" class="btn btn-primary btn-sm" value="Publish" asp-page-handler="Publish" />
        </div>
    </div>
</form>

@section Scripts {
    <script src="~/js/updateBody.js"></script>
}

BlogTemplate/Pages/Post.cshtml
@page "{id}/{slug}"
@model PostModel
@using Microsoft.AspNetCore.Mvc.RazorPages
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

@{
    ViewData["Title"] = Model.Post.Title;
}


<article>
    <div class="col-md-12">
        <h1>@Model.Post.Title</h1>
        <h5 name="date" class="date text-muted">@Model.Post.PubDate.ToString("MMM dd, yyyy")</h5>
        <p>@Model.HtmlBody()</p>
    </div>

    @if (User.Identity.IsAuthenticated)
    {
        <div class="col-md-12">
            <h4 class="text-primary"><a asp-page="/edit" asp-route-id="@Model.Post.Id.ToString("N")" asp-route-slug="@Model.Post.Slug">Edit Post</a></h4>
        </div>
        <form class="col-md-12" id="deletepost" method="post">
            @if (Model.Post.IsDeleted)
            {
                <div>
                    <input type="submit" name="undelete" class="btn btn-primary btn-sm" value="Undelete" asp-page-handler="UnDeletePost" />
                </div>
            }
            else
            {
                <div>
                    <input type="submit" name="delete" class="btn btn-primary btn-sm" value="Delete" asp-page-handler="DeletePost" />
                </div>
            }
        </form>
        <div class="col-md-6">
            <h2>Comments</h2>
            @if (Model.Post.Comments.Count == 0)
            {
                <p class="text-muted">No comments yet. Be the first to comment!</p>
            }
            @foreach (var comment in Model.Post.Comments)
            {
                string cssClass = comment.IsPublic ? "" : "deletedContent";
                <form id="form1" method="post">
                    <div class="@cssClass">
                        @if (comment.IsPublic)
                        {
                            <div class="well well-sm">
                                <h4 name="Comment-Title" class="commentTitle">@comment.AuthorName</h4>
                                <h6 name="Comment-Date" class="commentDate">@comment.PubDate.ToString("MMM dd, yyyy")</h6>
                                <p name="Comment-Body" class="commentBody">@comment.Body</p>
                                <input type="hidden" name="commentId" id="commentId" value="@comment.UniqueId" />
                                <input type="hidden" name="slug" value="@Model.Post.Slug" />
                                <input type="submit" name="delete" class="btn btn-primary btn-sm" value="Delete Comment" asp-page="ManageComment" asp-page-handler="DeleteComment" />
                            </div>

                        }
                        else
                        {
                            <div class="well well-sm">
                                <del class="h4">
                                    <h4 name="Comment-Title" class="commentTitle">@comment.AuthorName</h4>
                                    <h6 name="Comment-Date" class="commentDate">@comment.PubDate.ToString("MMM dd, yyyy")</h6>
                                </del>
                                <del><p name="Comment-Body" class="commentBody">@comment.Body</p></del>

                                <input type="hidden" name="commentId" id="commentId" value="@comment.UniqueId" />
                                <input type="hidden" name="slug" value="@Model.Post.Slug" />
                                <input type="submit" name="undelete" class="btn btn-primary btn-sm" value="Republish Comment" asp-page="ManageComment" asp-page-handler="UndeleteComment" /> 
                            </div>
                        }
                    </div>
                </form>
            }
        </div>
    }
    else
    {
        <div class="col-md-6">
            <h2>Comments</h2>
            @if (Model.Post.Comments.Count == 0)
            {
                <p class="text-muted">No comments yet. Be the first to comment!</p>
            }
            @foreach (var comment in Model.Post.Comments)
            {
                @if (comment.IsPublic)
                {
                    <form id="form1" method="post">
                        <div class="well well-sm">
                            <h4 name="Comment-Title" class="commentTitle">@comment.AuthorName</h4>
                            <h6 name="Comment-Date" class="commentDate">@comment.PubDate.ToString("MMM dd, yyyy")</h6>
                            <p name="Comment-Body" class="commentBody">@comment.Body</p>
                            <input type="hidden" name="commentId" id="commentId" value="@comment.UniqueId" />
                            <input type="hidden" name="slug" value="@Model.Post.Slug" />
                        </div>
                    </form>
                }
            }
        </div>
    }

    <hr class="commentsDivider" />
    @if (Model.Post.IsPublic && !Model.IsCommentsFull)
    {
        <div class="col-sm-6" style="height:6px;"></div>
        <div class="add-comment-form">
            <div class="col-md-6">
                <h3>Add Comment</h3>

                <div class="well">
                    <form id="comment-form" method="post">
                        <div class="form-group">
                            <label for="AuthorName">Name</label>
                            <input type="text" class="form-control" placeholder="" name="NewComment.AuthorName" />
                        </div>
                        <div class="form-group">
                            <label for="Body">Comment</label>
                            <textarea placeholder="" class="form-control" name="NewComment.Body"></textarea>
                        </div>
                        <input type="submit" name="publish" class="btn btn-primary btn-sm" value="Publish" asp-page-handler="PublishComment" />
                    </form>
                </div>
            </div>
        </div>
    }
</article>

BlogTemplate/Pages/Trash.cshtml
@page
@model TrashModel
@{
    ViewData["Title"] = "Trash Bin";

    if (!Model.PostSummaries.Any())
    {
    <div class="jumbotron">
        <p>There are no posts in your trash bin.</p>
    </div>
    }else
    {
        foreach (var post in Model.PostSummaries)
        {
            <article>
                <div class="col-md-12">
                    <h2><a asp-page="/post" asp-route-id="@post.Id.ToString("N")" asp-route-slug="@post.Slug">@post.Title</a></h2>
                    <h5 class="date text-muted">@post.PublishTime.ToString("MMM dd, yyyy")</h5>
                    <p class="lead">@post.Excerpt</p>
                    <h3><a asp-page="/post" asp-route-id="@post.Id.ToString("N")" asp-route-slug="@post.Slug"><span class="glyphicon glyphicon-comment"></span> @post.CommentCount</a></h3>
                </div>
            </article>
        }
    }
}